# Where things are
source:      ./public
destination: ./_site

highlighter: pygments

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      ['src','scripts']
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "md"

# Filtering Content
show_drafts: nil
limit_posts: 0
future:      true
unpublished: false

# Conversion
markdown:    kramdown
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"

# Serving
detach:  false
port:    4000
host:    localhost
baseurl: "" # does not include hostname