# Paths
destination: ./_site

# Template Vars
composer_version:    3.0.*
google_analytics_id: UA-43288838-2
repository:          https://github.com/kevinkhill/lavacharts

# Handling Reading
safe:         true
encoding:     "utf-8"
markdown_ext: "md"
keep_files:
 - js
 - css
 - images
 - fonts
 - api
exclude:
 - src
 - tests
 - configs
 - javascript
 - resources
 - node_modules
 - themes
 - CNAME
 - LICENSE
 - sami.cfg.php
 - gulpfile.js
 - '*.json'
 - '*.md'
 - '*.log'
 - '*.sublime-*'
 - Gemfile*
 - scotch.box
 - Vagrantfile
ignore_paths:
 - node_modules

# Filtering Content
show_drafts: nil
limit_posts: 0
future:      true
unpublished: false

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
kramdown:
  input: GFM

# Serving
detach:  false
port:    4000
host:    localhost
baseurl: ""
