# Where things are
destination: ./_site
highlighter: pygments

google_analytics_id: UA-43288838-2
repository: https://github.com/kevinkhill/lavacharts

# Handling Reading
safe:         true
exclude:      ['src','scripts']
keep_files:   [".git"]
encoding:     "utf-8"
markdown_ext: "md"

# Filtering Content
show_drafts: nil
limit_posts: 0
future:      true
unpublished: false

# Conversion
markdown:    kramdown
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"

# Serving
detach:  false
port:    4000
host:    localhost
baseurl: "/lavacharts" # does not include hostname