# Paths
destination: ./_site

# Template Vars
composer_version:    3.0.*
google_analytics_id: UA-43288838-2
repository:          https://github.com/kevinkhill/lavacharts

# Handling Reading
safe:         true
exclude:      ['src', 'javascript', 'resources', 'bower_components', 'node_modules', 'CONTRIBUTING.md', 'CHANGELOG.md', 'CNAME', 'LICENSE', 'gulpfile.js', '*.json', 'sami.cfg.php', '*.sublime-*', 'Gemfile*']
keep_files:   ['js', 'css', 'images', 'fonts']
encoding:     "utf-8"
markdown_ext: "md"

# Filtering Content
show_drafts: nil
limit_posts: 0
future:      true
unpublished: false

# Conversion
markdown:    kramdown
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"
kramdown:
  input: GFM

# Serving
detach:  false
port:    4000
host:    localhost
baseurl: ""
